# automatic testing with Travis CI!
language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add @lhci/cli@0.3.0-alpha.0
script:
  - yarn build
  - lhci autorun
addons:
  chrome: stable
notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
