# automatic testing with Travis CI!
language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add @lhci/cli@0.3.x
script:
  - yarn run build
  - lhci autorun
addons:
  chrome: stable
