name: GitHub Action to Run Tests

on: pull_request

# on:
#   pull_request:
#     types: [review_requested]

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # this will use https://github.com/actions/checkout
      - run: npm install
      - run: npm install @lhci/cli@0.3.0-alpha.0
      - run: npm run build
      - run: lhci autorun
