# name: GitHub Action to Run Tests

# on: pull_request

# # on:
# #   pull_request:
# #     types: [review_requested]

# jobs:
#   Run-Tests:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2 # this will use https://github.com/actions/checkout
#       - run: yarn
#       - run: yarn global add @lhci/cli@0.3.0-alpha.0
#       - run: yarn build
#       - run: lhci autorun
